import type { Metadata } from "next";
import "./globals.css";
import { geistSans } from "@/app/fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} antialiased bg-[#171717]`}
      >
        {children}
      </body>
    </html>
  );
}
